Normative: Switch syntax to ??.
tc39/proposal-optional-chaining pull request #48
Opened 2018-02-23 21:42 UTC by littledan

Follows the conclusion of the discussion at
https://github.com/tc39/proposal-optional-chaining/issues/34

2018-02-23 21:45 UTC, madskonradsen commented
That calls for a celebration! :)

2018-02-23 22:58 UTC, franklinyu commented on README.md
> +obj??.prop       // optional static property access
Align?

2018-02-24 00:09 UTC, Mouvedia commented
By "conclusion" he meant that [this comment](https://github.com/tc39/proposal-optional-chaining/issues/34#issuecomment-332649067) has the most upvotes. There's nothing official about it.

2018-02-24 09:14 UTC, littledan commented
@Mouvedia Something that's somewhat official about it is that the plan to switch to `??` was presented to TC39 in January 2018 with some discussion but overall a relatively supportive committee.

2018-02-24 09:16 UTC, littledan commented
Note that there is a parallel change for nullish coalescing at https://github.com/tc39/proposal-nullish-coalescing/pull/23 (to use `??:` syntax).

2018-02-26 09:33 UTC, hax commented
Too many `?`... and `??.` looks too close to `??:` which very harmful to readability...

`const city = staff??.company??.address??.city??:defaultCity;`



PS. Compare to my syntax suggestion:

`const city = staff!.company!.address!.country??defaultCity;`

2018-02-26 15:56 UTC, alangpierce commented
@hax Nullish coalescing is a binary operator, so it normally would be written with spaces:

```js
const city = staff??.company??.address??.city ??: defaultCity;
```

I think the spacing makes it reasonable to distinguish the operators from each other. As you mentioned in your original comment (https://github.com/tc39/proposal-optional-chaining/issues/34#issuecomment-350641176), `!.` conflicts with TypeScript, which seems really concerning to me, even if there are migration paths. My impression is that https://github.com/tc39/proposal-optional-chaining/issues/34 is still the best place to discuss syntax alternatives, and this PR discussion is best focused on the PR itself and whether it follows from previous discussions.

My reading of https://github.com/tc39/proposal-optional-chaining/issues/34 is that the four operators in this PR have by far the most support. See https://github.com/tc39/proposal-optional-chaining/issues/34#issuecomment-333413308 and the comments immediately above and below it for a poll of various alternatives. (And, as mentioned, TC39 seems to be in favor of this syntax, and they're the ones actually making the decision.) Hopefully most people are at least agreed that this is an improvement over the original `?.`, `?.[`, `?.(`, which is what this PR is replacing.

2018-02-26 17:08 UTC, lehni commented
Even with spaces, I still prefer @hax's syntax suggestion, and agree that the similarity between the two operators is rather confusing and doesn't help quick reading / understanding of code. This just looks much more readable to me:

```js
const city = staff!.company!.address!.country ?? defaultCity;
```

And so does this:

```js
const city = staff?.company?.address?.country ?? defaultCity;
```

2018-02-26 18:24 UTC, claudepache commented
@hax, @lehni Discussion about the syntax must go in #34, not here. (But please do not repeat arguments you’ve already done.)

2018-02-26 18:28 UTC, littledan commented
@claudepache What do you think of this PR?

2018-02-26 18:41 UTC, claudepache commented
@littledan 
> What do you think of this PR?

I haven’t had time to review it yet. But yes, I'm favourable to switch to that syntax, on condition that the syntax of nullish-coalescing is also changed (tc39/proposal-nullish-coalescing#23 or anything else).

2018-02-26 18:43 UTC, hax commented
@alangpierce  Coding style can help, but these too close symbols also restrict the options of coding style. For example, you can not also add spaces around `??.` for any reason:
```
staff??.company_name??.very_long_address??.#private_field // not very clear
```
```
staff ??. company_name ??. very_long_address ??. #private_field // better
```
```
staff ??. company_name ??. very_long_address ??. #private_field ??: default_value // unfortunate...
```

Try two spaces...
```
staff ??. company_name ??. very_long_address ??. #private_field  ??:  default_value 
```

Maybe we need three?
```
staff ??. company_name ??. very_long_address ??. #private_field   ??:   default_value
```

...So, see the problem?

Note, I just use `!.` for comparison because I believe it's the best option, but `?&` also better than current combination in readability. Eg.
```
staff ?&. company_name ?&. very_long_address ?&. #private_field ?? default_value
```
And `?>` (though it may have other problems)
```
staff ?>. company_name ?>. very_long_address ?>. #private_field ?? default_value
```

---

> My reading of #34 is that the four operators in this PR have by far the most support.

Unfortunately the supporters all ignore the readability problem of `??.` with `??:`.

> My impression is that #34 is still the best place to discuss syntax alternatives

The thread is already too long to catch. So maybe we should create a new issue.

2018-03-07 16:01 UTC, Tiedye commented
What conclusion https://github.com/tc39/proposal-optional-chaining/issues/51 ?

2018-03-07 16:39 UTC, ljharb approved these changes

2018-03-09 18:51 UTC, claudepache requested changes
Some corrections.

Also, given the strong resistance against that syntax, we should probably wait that TC39 confirms whether it is the way to go.

2018-03-09 18:51 UTC, claudepache commented on README.md
> +An earlier version of this proposal used `??.` for the optional chaining operator, with `??[` for dynamic property access and `??(` for optional function/method calls. The switch to two question mark
To zealous search-and-replace? Replace back `??.` / `??[`/`??(` with`?.` / `?.[` / `?.(` in that sentence.

2018-03-09 18:51 UTC, claudepache commented on README.md
> +* constructor or template literals in/after an Optional Chain: `new a??b()`, ``a??.b`{c}` ``
`new a??.b()`

2018-03-09 18:51 UTC, claudepache commented on README.md
> -<dt>obj?.[expr]  and  func?.(arg)  look ugly. Why not use  obj?[expr]  and  func?(arg)  as does &lt;language X>?
Instead of deleting that FAQ item, let’s replace it with: 

> obj??.prop, obj??[expr] and func??(arg) look like null coalescing in &lt;language X>. Why not use  obj?.prop, obj?[expr]  and  func?(arg)  as does &lt;language X>?

Further adaptations below.

2018-03-09 18:51 UTC, claudepache commented on README.md
> -We don’t use the `obj?[expr]` and `func?(arg)` syntax, because of the difficulty for the parser to efficiently distinguish those forms from the conditional operator, e.g., `obj?[expr].filter(fun):0`
Let’s be more affirmative: ”We can’t use...”

2018-03-09 18:51 UTC, claudepache commented on README.md
> -Alternative syntaxes for those two cases each have their own flaws; and deciding which one looks the least bad is mostly a question of personal taste. Here is how we made our choice:
As a temporary measure, replace with: ”[TODO: explain the rationale and the tradeoffs behind the choice of `??`]” (and delete the two bullets just below).

2018-03-09 18:51 UTC, claudepache commented on spec.html
> +  <p>For the syntax, we use the `??.` token. An earlier version of this proposal used `?.`</p>
In fact, we use three tokens, namely `??.`, `??[` and `??(`. I propose (don’t hesitate to improve the text):

> For the syntax, we use the `??` sequence of characters for suggesting ”optional”. An earlier version of this proposal used the `?.` token for that purpose.

2018-03-09 18:51 UTC, claudepache commented on spec.html
> +        `??.` `??(` `??[`
Should be surrounded by &lt;ins>.

2018-03-09 18:51 UTC, claudepache commented on spec.html
> +        `??(` ArgumentsList[?Yield, ?Await] `,`? `)
You missed `??()`; that is to say, ArgumentsList is optional, but the optional comma is forbidden if ArgumentsList is omitted:

      `??(`  `)`
      `??(` ArgumentList[?Yield, ?Await] `,`? `)`

2018-03-09 18:51 UTC, claudepache commented on spec.html
> +        <emu-grammar>OptionalChain : `??(` ArgumentsList `,` `)` </emu-grammar>
I’d say (as above):

```
  <emu-grammar>
    OptionalChain :
      `??(` `)`
      `??(` ArgumentList[?Yield, ?Await] `,`? `)`
   </emu-grammar>
```

2018-03-09 18:51 UTC, claudepache commented on spec.html
> +            `??(` ArgumentsList `,`? `)`
As above.

```
    OptionalChain :
      `??(` `)`
      `??(` ArgumentsList `,`? `)`
      OptionalChain Arguments
```

2018-03-13 16:42 UTC, jrista commented
Are we seriously considering ??. and ??: as better than ?. and ?? for his proposal? I don't know where anyone is seeing a consensus that ??. is more desired or accepted than ?. by the community at large. In fact, it seems that ?. is far more accepted based on #51. I find ??. to be very heavy and unsightly, and in all honesty don't really want to be writing code littered with this verbose operator...

2018-03-13 16:44 UTC, gisenberg commented
@jrista Please use #34 for feedback related to syntax.

2018-03-13 17:29 UTC, jrista commented
I've commented in the other thread, but I have to say, this PR and the direction this proposal is now taking is very, very concerning. Ergonomics, understandability, verbosity. We are starting to head in the wrong direction on all fronts, and I truly hope this PR does not get merged.

2018-03-28 16:57 UTC, claudepache commented
@littledan If you still think that this PR should be merged, could you apply the requested changes?

2018-03-30 18:19 UTC, jrista commented
I don't know that the debate over the operator has been settled. At this time, it still appears as though, despite it's supposed inconsistency, ?./?? is still by far the more preferred operator. Discussions on the operators seem to have stalled, but I don't believe that means the debate has ended, nor that ??. is what we should be using.

2018-03-30 20:13 UTC, gisenberg commented
I presented both options to the committee last week and strongly advocated for the current syntax, calling out the strong community support. Both proposals had hard vetoes that prevented stage advancement: 
* `?.` because of inconsistency and overloading the meaning of `.` for bracket/method access.
* `??.` because of the impact to the token for the null coalescing operator. 

Paring back the proposal to only support `?.` and opt-out of bracket and method access also received strong opposition. The absence of symmetry between member and bracket access and the choice of token ruling out future extensions to optional method/bracket access were cited as reasons that would block advancement of only `?.`.

There was no strong opposition to `??.` `??(` `??[` assuming null coalescing could find a better token (eg: not `??:`). `???` and `|||` were floated as possible alternatives.

Looking at the poll results for possible token options, there are really only two options and we've definitively ruled out one. I suspect that hard constraints settle the syntax debate, but I'm open to alternatives.

2018-04-03 22:55 UTC, littledan commented
@rattrayalex Some people didn't like the colon. Not sure what more there is to say; I guess it makes it less analogous to `||`.

2018-04-04 15:05 UTC, rattrayalex commented
Cool, thanks @littledan. Perhaps they could be persuaded (much of es syntax design seems very constraint-driven). I assume you're working with the fine folks over at optional chaining. May be worth opening an informal bikeshed poll over on the other repo.

2018-11-30 22:18 UTC, selipso commented
IMO null coalescing should be ||| as it's the only one that makes sense and leaves open the possibility to &&& (where 0 and '') are considered truthy.

That would also open up `??` to optional chaining without having that pesky `.` for square bracket notation.

2018-11-30 23:03 UTC, ljharb commented
@selipso in the TC39 meeting this week it was brought up that if `===` is a stricter `==`, then `|||` would be a stricter `||`, and since `||` deals with truthiness, `|||` would need to deal with `true` - a compelling argument that seemed to convince many people that `|||` is not an option for this proposal.

2018-12-01 00:04 UTC, selipso commented
Then by that logic `|||` is 'stricter' than `||` because nullish types are more limiting than the loosey-goosey `||` where `!(0 || '') === true`. Perfectly intuitive to me and easily explainable to even my high school students that I teach programming to.

2018-12-01 01:39 UTC, hax commented
@selipso I think we should learn from failure of visually too close operators. The mainstream coding style now only allow `===` and forbidden `==` to avoid the confusion and accidently typos, there is also a rule which forbidden `|` and `&` to avoid potential confusion/typo with `||` and `&&`, so it's hard to convince the community adding `|||` (and adding `&&&` for consistency) would be a good idea.

Note we can forbidden `==` because all `==` use cases could be converted to `===` with explicit type cast. We can forbidden `&` and `|` because most modules do not need bitwise operations, and we can choose to opt in if we really need bitwise ops in special modules. But we can't forbidden `||` because it's very correct to use `||` as logical operator, both `||` and `|||` have very common use cases. This is why we need null coalescing operator, and I think as the motivation of some linter rules suggest, we'd better use syntax which have enough distance to avoid the confusion and typo.

2018-12-01 02:03 UTC, selipso commented
@hax I, for one, would be fine with `||` being “less recommended” compared to `|||`. The concept of ‘falsy’ is a sticking point in JavaScript for both new and experienced programmers alike (esp. coming from C). I still see codebases with both `==` and `===` used cleverly and also appropriately. It will never be forbidden to use older syntax, but when some operator does something very similar to another operator, there is no need to add a mental switching cost with a different control character.

This would also free up optional chaining (which IMO is a more exciting and practical language feature) to use either `?.` or `??.`, or even both! Makes everyone happy.

2018-12-07 16:38 UTC, jrista commented
@hax There are definitely valid current uses of ==, and not all == should nor could be converted to === and still maintain the desired functionality. I commonly use `variable == null` to do null or undefined checks rather than falsy checks, for example.

2019-01-02 22:15 UTC, jrista commented
@hax It may be that you can, one way or another, find a way to eliminate ALL `==` and replace them with `===`. Is that always the best way? It can needlessly increase the verbosity of code...and depending on the project and the nature of the data it may be very common to need to do null/undefined checks, and pounding out the full `variable === null || variable === undefined` quickly becomes tedious and mind numbing. 

I find value in `==` in some cases, though, beyond just the `variable == null` case. Another valid example, IMO, is when you are working with "dirty data", which sometimes occurs with existing APIs. I've had to write code over the years that needs to work with APIs that are not properly versioned in a detectable way, for which multiple versions may be deployed and used and poor version management coupled with unexpected API deployments can wreak havoc, and where certain data such as numbers may be quoted or not, and where magic numbers are often used (ugh, old APIs...). For example `0 == '0'` can be quite useful, since the data may be `'0'` or `0` depending on the API version.

I guess I try to be pragmatic rather than dogmatic when it comes to which operator to use. When I use `==`, I ALWAYS comment in the code as to why, though, as there have been times when I've worked with more dogmatic developers who will happily convert every `==` they see it to `===` without considering the implications. ;) As often ends up being the case, I am able to introduce a little bit of pragmatism into those dogmatic individuals and simplify their lives a little bit once they learn how useful `==` can be in these special cases. ;D (And yes, I would consider them special cases...special, and completely valid.)

2019-01-03 16:57 UTC, jrista commented
@hax: I would not simply do `a === Number(b)` either, not without a comment, as I have also had other developers come along and change that to just `a === b`, seeing only one form of the data, thinking the `Number(b)` was unnecessary. 🤷‍♂️

2019-01-03 16:59 UTC, ljharb commented
A developer who would think it’s safe to casually remove an explicit type coercion likely would also casually remove a comment, believing it to be irrelevant :-)

2019-03-29 12:11 UTC, 0rvar commented
I do not like the change to `??.` at all. I fail to see what the improvement is over `?.`, and it is much more verbose.

2019-03-29 12:50 UTC, MatthiasKunnen commented
@0rvar, I believe it was already decided to seek stage advancement with the current spec. The current spec uses ?.  
It is my understanding that this pr will not be merged. After stage 2 is reached this repository will undergo some cleaning and PRs and issues will be closed.

This is a summary of issues I've read over the months.

2019-04-05 18:25 UTC, littledan commented
I think many of us are leaning more towards `?.` these days, so I'm closing this PR for clarity. We can reopen it if we see a need to revisit it later.

2019-04-05 18:25 UTC, closed without merging